use amaresh;
select*from cuku;
select name, gender from cuku;
select*from cuku where id >'5';
select*from cuku where date_of_birth>'2000-06-01';
select*from cuku where date_of_birth<'2000-06-01';
select*from cuku where gender!='male/female';
select*from cuku where date_of_birth is null;
select*from cuku where date_of_birth>'2000-06-01';
select*from cuku where gender="female" and date_of_birth>'2001-01-26';
select*from cuku where gender="male" and salary>'23000';
select*from cuku where gender="male" or salary>'23000';
select*from cuku where date_of_birth="2000-03-01";
select*from cuku where gender="male" or salary>'23000'order by date_of_birth desc;
select*from cuku where gender ="male" or salary>"23000" order by date_of_birth desc limit 5;
select*from cuku where gender ="make" or salary >"23000" order by date_of_birth asc limit 5;
select*from cuku order by salary  desc;
select*from cuku order by name  asc;
update cuku set salary="70000" where id="5";
update cuku set name="Amresh",date_of_birth="2005-01-19" where id ="1";
update cuku set name="Amaresh",email="mohapatraamaresh141@gmail.com" where id ="1";
select*from cuku where salary <60000;
set sql_safe_updates=0;
update cuku set salary= salary+10000 WHERE salary<60000;
update cuku set salary=salary+2;
select*from cuku where gender="female" and salary <65000;
delete from cuku where gender="female" and salary <65000;