use amaresh;
select*from cuku;
-- insert into cuku (id,name,email,gender,date_of_birt,salary) values(1,"Amaresh","mohapatraamaresh141@gmail.com","male",2005-01-19,60001);
-- alter table cuku add constraint unique_email unique(email); 
-- select*from cuku;
select count(*) from cuku;
select count(*) from cuku where gender="female";
select count(*) from cuku where gender="male";
select min(salary) as min_salary, max(salary) as max_salary from cuku;
select sum(salary) as total from cuku;
select avg(salary) as avg_sal from cuku;
select gender,avg(salary) as avg_salary from cuku group by gender;
select id,gender,avg(salary) as avg_salary from cuku group by id;
select name,length(name) as name_length from cuku;
select gender,name,length(name) as name_length from cuku;
select id,gender,name,length(name) as name_length from cuku;
select id,gender,lower(name) as lower_name,length(name) as length_name from cuku;
select id,gender,upper(name) as upper_name,length(name) as length_name from cuku;
select id,gender,lower(name) as lower_name,concat(lower(name),"5677") as username ,length(name) as length_name from cuku;
select id,gender,upper(name) as list_name,concat(lower(name),"@123") as username,length(name) as length_name from cuku;
select id,upper(gender) as list_gender,upper(name) as list_name,concat(lower(name),"@123") as username,length(name) as length_name,now()as time from cuku;
select datediff(curdate(),date_of_birth) as days from cuku;
select name,datediff(curdate(),date_of_birth) as days from cuku;
select name, salary,round(salary) as rounded,floor(salary) as floored,ceil(salary) as celled from cuku;
select id,mod(id,2) as remainder from cuku;
select name,gender,if(gender='female','yes','no') as is_female from cuku;
select name,gender,if(gender='male','yes','no') as if_male from cuku;
select*from cuku  order by salary desc;
select name,salary from cuku order by salary desc limit 2,2;

