use amaresh;
select*from lele;
select*from addresses;
select lele.name,addresses.city from lele inner join addresses on lele.id=addresses.user_id;
select lele. salary,email,addresses.pincode from lele inner join addresses;
select lele.id,name,email,addresses.city,state,pincode from lele inner join addresses on lele.id=addresses.user_id;
use akm;
select*from ipl2;
select*from ipl2 where Player_Name ="Shikhar Dhawan";
alter table ipl2 rename column 'Player Name' to player_name varchar(100);
-- describe ipl2;
-- select version();
show create table ipl2;
