use akm;
select*from ipl2;
rename table ipl2 to ipl3;
select*from ipl3;
alter table ipl3 add column salary varchar(100);
alter table ipl3 drop column salary;
alter table ipl3 modify column	 salary varchar(100) after player_no;
select*from ipl3 where player_type="Allrounder";
select*from ipl3 where player_type="Bowler ";
select*from ipl3 where player_type="Batter";
select*from ipl3 where player_type="Bowler " and Matches_Played < ('50');
select*from ipl3 where Player_type="Batter" and Nationality="Indian";
-- select*from ipl3 where Player Name="
select count(*) run from ipl3;
select*from ipl3 where Player_Type="Batter" or Runs<200 order by Matches_Played asc ;
select*from ipl3 where Runs=0;
select*from ipl3 where Team="Bangalore" and Runs>2000 order by Strike_Rate asc;
select*from ipl3 where Strike_Rate>190;
select*from ipl3;
select count(*) from ipl3 where Player_Type="Batter";